spring:
  datasource:
    url: jdbc:postgresql://ec2-34-233-157-189.compute-1.amazonaws.com:5432/dm6mfvrr6hkvr
    username: ecmmdolerrtbkv
    password: 9980967df1e953365277a3bfdb65647fe99e2aea1ee9de8804df1aa0fc985a6d
  jpa:
    hibernate:
      ddl-auto: update


    properties:
      hibernate:
        metadata_builder_contributor: com.dreesis.articles.utils.SqlFunctionsMetadataBuilderContributor




server:
  port: 9090



